[GLOBAL]
remote_execution = true
remote_execution_server = "build.toolchain.com:443"
remote_store_server = "build.toolchain.com:443"
remote_ca_certs_path = "/etc/ssl/certs/ca-certificates.crt"
remote_instance_name = "main"
remote_execution_extra_platform_properties = [
  # This allows network requests, e.g. to resolve dependencies with Pex.
  "execution-policy=network",
  "execution-policy=container-image=pants-remote-execution:47f364584e3e4bd8c8ecf71639efaec34133e3a9",
]
process_execution_remote_parallelism = 6

[python-setup]
interpreter_search_paths = [
  # These are the interpreter paths we set up on the remote container.
  "/pyenv-docker-build/versions/3.8.5/bin:/pyenv-docker-build/versions/3.7.8/bin:/pyenv-docker-build/versions/3.6.11/bin:/pyenv-docker-build/versions/2.7.18/bin",
]

[python-native-code]
ld_flags = []
cpp_flags = []

